from typing import Any, Protocol


class RegistryService(Protocol):
    def load(self) -> None: ...

    def list_tools(self) -> list[dict[str, Any]]: ...

    def get_tool(self, name: str) -> dict[str, Any] | None: ...

    def get_descriptions(self) -> list[tuple[str, str]]: ...
