const { app, BrowserWindow, session, netLog } = require('electron')
const path = require('path')
const out = path.join(__dirname, 'netlog.json')
app.whenReady().then(async () => {
  console.log('VERSIONS', JSON.stringify(process.versions))
  await session.defaultSession.setProxy({ mode: 'system' })
  console.log('PROXY_GOOGLE', await session.defaultSession.resolveProxy('https://www.google.com'))
  console.log('PROXY_SPEECH', await session.defaultSession.resolveProxy('https://www.google.com/speech-api/v2/recognize'))
  session.defaultSession.webRequest.onBeforeRequest((details, callback) => { console.log('WEBREQUEST', details.method, details.url); callback({}) })
  app.on('login', (event, webContents, details, authInfo, callback) => { console.log('LOGIN', JSON.stringify({ url: details.url, isProxy: authInfo.isProxy, host: authInfo.host, scheme: authInfo.scheme, realm: authInfo.realm })); callback() })
  app.on('certificate-error', (event, webContents, url, error, certificate, callback) => { console.log('CERT_ERROR', url, error, certificate && certificate.subjectName); callback(false) })
  await netLog.startLogging(out, { captureMode: 'includeSensitive' })
  const win = new BrowserWindow({ width: 900, height: 700, show: true, webPreferences: { nodeIntegration: false, contextIsolation: true } })
  win.webContents.on('console-message', (_event, level, message) => console.log('RENDERER', level, message))
  session.defaultSession.setPermissionRequestHandler((_wc, permission, callback) => { console.log('PERMISSION', permission); callback(permission === 'media' || permission === 'speech-recognition') })
  await win.loadFile(path.join(__dirname, 'index.html'))
  setTimeout(async () => { try { await netLog.stopLogging(); console.log('NETLOG_DONE', out) } catch (err) { console.log('NETLOG_STOP_ERR', err.message) } app.quit() }, 20000)
})
